In [1]:
# Import the necessary libraries

import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings('ignore')

import seaborn as sns

from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn import linear_model
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

import matplotlib.pyplot as plt
%matplotlib inline


# importing the lib to use the log reg
from sklearn.linear_model import LogisticRegression

In [2]:
# Load the we_fn_use_c_marketing_customer_value_analysis.csv into the variable customer_df

customer_df = pd.read_csv("/Users/giulianamiranda/Documents/Labs/lab-cleaning-numerical-data/files_for_lab/we_fn_use_c_marketing_customer_value_analysis.csv", sep = ',')

# standardizing the columns names

cols = []

for a in range(len(customer_df.columns)):
    cols.append(customer_df.columns[a].lower().replace(' ', '_'))
    
customer_df.columns = cols

Instructions
Import the necessary libraries load the data and start a new notebook. Using the same data as the previous lab: we_fn_use_c_marketing_customer_value_analysis.csv

Find all of the categorical data. Save it in a categorical_df variable.

Check for NaN values and decide what to do with them, do it now.

Check all unique values of columns.

Check dtypes. Do they all make sense as categorical data?

Does any column contain alpha and numeric data? Decide how to clean it and do it now.

Would you choose to do anything else to clean or wrangle the categorical data? Comment your decisions and do it now.

Compare policy_type and policy. What information is contained in these columns. Can you identify what is important?

Check number of unique values in each column, can they be combined in any way to ease encoding? Comment your thoughts and make those changes.

Save the cleaned catagorical dataframe as categorical.csv You will use this file again this week.

In [3]:
# Find all of the categorical data. Save it in a categorical_df variable.

categorical_df = customer_df.select_dtypes(include=[object])

# Check for NaN values and decide what to do with them, do it now.

categorical_df.isna().sum()

# There ar no missing value

customer             0
state                0
response             0
coverage             0
education            0
effective_to_date    0
employmentstatus     0
gender               0
location_code        0
marital_status       0
policy_type          0
policy               0
renew_offer_type     0
sales_channel        0
vehicle_class        0
vehicle_size         0
dtype: int64

In [4]:
# Check all unique values of columns.

def unique_values (df):
    for column in df.columns:
        print('Unique value of', column, 'column is', df[column].nunique())

In [5]:
unique_values(categorical_df)

Unique value of customer column is 9134
Unique value of state column is 5
Unique value of response column is 2
Unique value of coverage column is 3
Unique value of education column is 5
Unique value of effective_to_date column is 59
Unique value of employmentstatus column is 5
Unique value of gender column is 2
Unique value of location_code column is 3
Unique value of marital_status column is 3
Unique value of policy_type column is 3
Unique value of policy column is 9
Unique value of renew_offer_type column is 4
Unique value of sales_channel column is 4
Unique value of vehicle_class column is 6
Unique value of vehicle_size column is 3

In [6]:
# Check dtypes. Do they all make sense as categorical data?
# Yes, they do. IÂ´d say the effective_to_date is the one that makes less sense

categorical_df.dtypes

customer             object
state                object
response             object
coverage             object
education            object
effective_to_date    object
employmentstatus     object
gender               object
location_code        object
marital_status       object
policy_type          object
policy               object
renew_offer_type     object
sales_channel        object
vehicle_class        object
vehicle_size         object
dtype: object

In [7]:
# Does any column contain alpha and numeric data? Decide how to clean it and do it now.
# There are no column with alpha and numeric data

def alpha_and_numeric(df):
    for column in df.columns:
        for value in df[column]:
            if value.isalpha() and value.isnumeric():
                return column  

    return 'There are none'  

# Example usage with categorical_df
result = alpha_and_numeric(categorical_df)
print("Contains alpha and numeric data:", result)

Contains alpha and numeric data: There are none

In [8]:
# Would you choose to do anything else to clean or wrangle the categorical data? 
# Comment your decisions and do it now.

categorical_df.head(50)

# No, I think it is already clean

,customer,state,response,coverage,education,effective_to_date,employmentstatus,gender,location_code,marital_status,policy_type,policy,renew_offer_type,sales_channel,vehicle_class,vehicle_size
0,BU79786,Washington,No,Basic,Bachelor,2/24/11,Employed,F,Suburban,Married,Corporate Auto,Corporate L3,Offer1,Agent,Two-Door Car,Medsize
1,QZ44356,Arizona,No,Extended,Bachelor,1/31/11,Unemployed,F,Suburban,Single,Personal Auto,Personal L3,Offer3,Agent,Four-Door Car,Medsize
2,AI49188,Nevada,No,Premium,Bachelor,2/19/11,Employed,F,Suburban,Married,Personal Auto,Personal L3,Offer1,Agent,Two-Door Car,Medsize
3,WW63253,California,No,Basic,Bachelor,1/20/11,Unemployed,M,Suburban,Married,Corporate Auto,Corporate L2,Offer1,Call Center,SUV,Medsize
4,HB64268,Washington,No,Basic,Bachelor,2/3/11,Employed,M,Rural,Single,Personal Auto,Personal L1,Offer1,Agent,Four-Door Car,Medsize
5,OC83172,Oregon,Yes,Basic,Bachelor,1/25/11,Employed,F,Rural,Married,Personal Auto,Personal L3,Offer2,Web,Two-Door Car,Medsize
6,XZ87318,Oregon,Yes,Basic,College,2/24/11,Employed,F,Suburban,Married,Corporate Auto,Corporate L3,Offer1,Agent,Four-Door Car,Medsize
7,CF85061,Arizona,No,Premium,Master,1/18/11,Unemployed,M,Urban,Single,Corporate Auto,Corporate L3,Offer1,Agent,Four-Door Car,Medsize
8,DY87989,Oregon,Yes,Basic,Bachelor,1/26/11,Medical Leave,M,Suburban,Divorced,Corporate Auto,Corporate L3,Offer1,Agent,Four-Door Car,Medsize
9,BQ94931,Oregon,No,Extended,College,2/17/11,Employed,F,Urban,Married,Special Auto,Special L2,Offer2,Branch,Four-Door Car,Medsize
10,SX51350,California,No,Basic,College,2/21/11,Unemployed,M,Suburban,Single,Personal Auto,Personal L3,Offer1,Agent,Four-Door Car,Small
11,VQ65197,California,No,Basic,College,1/6/11,Unemployed,F,Suburban,Married,Personal Auto,Personal L3,Offer2,Agent,SUV,Medsize
12,DP39365,California,No,Premium,Master,2/6/11,Employed,M,Urban,Married,Corporate Auto,Corporate L1,Offer2,Agent,Four-Door Car,Medsize
13,SJ95423,Arizona,Yes,Basic,High School or Below,1/10/11,Employed,M,Suburban,Married,Corporate Auto,Corporate L3,Offer2,Branch,SUV,Medsize
14,IL66569,California,No,Basic,College,1/18/11,Employed,M,Urban,Single,Corporate Auto,Corporate L3,Offer4,Call Center,Four-Door Car,Medsize
15,BW63560,Oregon,No,Basic,Bachelor,1/17/11,Employed,F,Rural,Married,Corporate Auto,Corporate L2,Offer2,Branch,Four-Door Car,Medsize
16,FV94802,Nevada,No,Basic,High School or Below,2/6/11,Medical Leave,M,Suburban,Married,Personal Auto,Personal L3,Offer2,Call Center,Two-Door Car,Medsize
17,OE15005,California,No,Basic,College,1/5/11,Medical Leave,M,Suburban,Married,Personal Auto,Personal L2,Offer3,Call Center,SUV,Medsize
18,WC83389,Oregon,No,Basic,College,2/27/11,Employed,M,Urban,Married,Personal Auto,Personal L2,Offer2,Branch,Four-Door Car,Medsize
19,FL50705,California,No,Premium,High School or Below,1/14/11,Employed,F,Suburban,Married,Corporate Auto,Corporate L2,Offer1,Call Center,Four-Door Car,Small
20,ZK25313,Oregon,No,Basic,High School or Below,2/19/11,Employed,M,Suburban,Single,Personal Auto,Personal L2,Offer1,Branch,Two-Door Car,Medsize
21,SV62436,Washington,No,Extended,Bachelor,1/21/11,Disabled,F,Suburban,Divorced,Personal Auto,Personal L3,Offer4,Call Center,Four-Door Car,Medsize
22,YH23384,Arizona,Yes,Basic,Bachelor,1/26/11,Medical Leave,M,Suburban,Divorced,Personal Auto,Personal L3,Offer1,Agent,Four-Door Car,Medsize
23,TZ98966,Nevada,No,Basic,Bachelor,2/24/11,Unemployed,F,Suburban,Single,Corporate Auto,Corporate L3,Offer1,Branch,Four-Door Car,Medsize
24,HM55802,California,No,Basic,Bachelor,2/5/11,Disabled,F,Suburban,Married,Corporate Auto,Corporate L2,Offer2,Branch,Four-Door Car,Medsize
25,FS42516,Oregon,No,Basic,College,1/29/11,Employed,M,Suburban,Married,Personal Auto,Personal L3,Offer2,Call Center,Four-Door Car,Large
26,US89481,California,No,Premium,Bachelor,2/28/11,Unemployed,F,Suburban,Single,Personal Auto,Personal L3,Offer1,Agent,Four-Door Car,Small
27,HO30839,Washington,No,Extended,Master,2/12/11,Disabled,F,Urban,Married,Corporate Auto,Corporate L1,Offer1,Branch,SUV,Medsize
28,GE62437,Arizona,No,Premium,College,2/2/11,Employed,F,Suburban,Single,Personal Auto,Personal L3,Offer1,Call Center,Four-Door Car,Large
29,EJ77678,Oregon,No,Extended,Master,2/7/11,Employed,F,Suburban,Married,Personal Auto,Personal L3,Offer2,Branch,Four-Door Car,Small
30,SV85652,Arizona,No,Basic,College,2/28/11,Employed,M,Suburban,Married,Personal Auto,Personal L2,Offer4,Call Center,Four-Door Car,Small
31,UL64533,Nevada,No,Extended,High School or Below,1/22/11,Employed,M,Urban,Married,Corporate Auto,Corporate L2,Offer2,Agent,Luxury SUV,Medsize
32,PF41800,California,No,Basic,Bachelor,1/25/11,Unemployed,M,Urban,Married,Personal Auto,Personal L3,Offer1,Call Center,Four-Door Car,Medsize
33,AO98601,Washington,No,Basic,Bachelor,1/18/11,Employed,M,Suburban,Married,Corporate Auto,Corporate L2,Offer1,Agent,Two-Door Car,Small
34,SK67821,Oregon,No,Basic,Bachelor,2/13/11,Employed,F,Rural,Married,Corporate Auto,Corporate L1,Offer3,Web,Four-Door Car,Medsize
35,YV55495,Arizona,No,Basic,High School or Below,1/15/11,Employed,F,Urban,Married,Personal Auto,Personal L1,Offer1,Branch,Four-Door Car,Medsize
36,KY38074,California,No,Premium,Bachelor,1/8/11,Employed,M,Suburban,Married,Personal Auto,Personal L3,Offer1,Agent,Four-Door Car,Small
37,DM79012,Oregon,No,Extended,Master,2/6/11,Employed,F,Suburban,Married,Personal Auto,Personal L3,Offer2,Web,Four-Door Car,Small
38,CM61827,Oregon,No,Extended,Bachelor,1/25/11,Unemployed,M,Suburban,Single,Personal Auto,Personal L2,Offer3,Agent,Two-Door Car,Small
39,WC35801,Arizona,No,Basic,High School or Below,2/7/11,Employed,M,Rural,Divorced,Personal Auto,Personal L3,Offer1,Call Center,Four-Door Car,Medsize
40,QG25316,Nevada,No,Basic,High School or Below,1/18/11,Unemployed,F,Suburban,Married,Corporate Auto,Corporate L3,Offer3,Call Center,Two-Door Car,Medsize
41,MB98372,Oregon,Yes,Basic,College,1/11/11,Employed,F,Rural,Single,Corporate Auto,Corporate L3,Offer2,Agent,Two-Door Car,Medsize
42,IL19217,California,Yes,Extended,Bachelor,1/28/11,Employed,F,Suburban,Married,Personal Auto,Personal L2,Offer2,Agent,Four-Door Car,Small
43,SR38658,Arizona,No,Basic,High School or Below,2/8/11,Employed,M,Suburban,Married,Personal Auto,Personal L2,Offer4,Agent,Sports Car,Medsize
44,DH41343,Washington,No,Basic,College,2/23/11,Employed,M,Suburban,Married,Special Auto,Special L2,Offer2,Call Center,Four-Door Car,Large
45,HG65722,Oregon,No,Premium,Doctor,1/25/11,Disabled,F,Rural,Married,Personal Auto,Personal L2,Offer1,Branch,SUV,Medsize
46,BU27331,Arizona,No,Basic,Bachelor,1/31/11,Unemployed,M,Suburban,Single,Personal Auto,Personal L3,Offer3,Call Center,Four-Door Car,Medsize
47,XM45289,Oregon,No,Basic,High School or Below,1/2/11,Employed,F,Suburban,Single,Personal Auto,Personal L2,Offer4,Agent,Two-Door Car,Medsize
48,KP34198,California,No,Extended,Bachelor,2/7/11,Unemployed,F,Suburban,Married,Corporate Auto,Corporate L2,Offer2,Call Center,Four-Door Car,Medsize
49,SH90947,Arizona,No,Basic,High School or Below,1/18/11,Unemployed,F,Suburban,Married,Personal Auto,Personal L2,Offer4,Branch,Four-Door Car,Medsize

In [9]:
# Compare policy_type and policy. What information is contained in these columns. 
# Can you identify what is important?

categorical_df[['policy_type', 'policy']].head(50)

#  Both columns have information the the policy type of the insurance
# While the 'policy_type' is broader, the 'policy'

       policy_type        policy
0   Corporate Auto  Corporate L3
1    Personal Auto   Personal L3
2    Personal Auto   Personal L3
3   Corporate Auto  Corporate L2
4    Personal Auto   Personal L1
5    Personal Auto   Personal L3
6   Corporate Auto  Corporate L3
7   Corporate Auto  Corporate L3
8   Corporate Auto  Corporate L3
9     Special Auto    Special L2
10   Personal Auto   Personal L3
11   Personal Auto   Personal L3
12  Corporate Auto  Corporate L1
13  Corporate Auto  Corporate L3
14  Corporate Auto  Corporate L3
15  Corporate Auto  Corporate L2
16   Personal Auto   Personal L3
17   Personal Auto   Personal L2
18   Personal Auto   Personal L2
19  Corporate Auto  Corporate L2
20   Personal Auto   Personal L2
21   Personal Auto   Personal L3
22   Personal Auto   Personal L3
23  Corporate Auto  Corporate L3
24  Corporate Auto  Corporate L2
25   Personal Auto   Personal L3
26   Personal Auto   Personal L3
27  Corporate Auto  Corporate L1
28   Personal Auto   Personal L3
29   Personal Auto   Personal L3
30   Personal Auto   Personal L2
31  Corporate Auto  Corporate L2
32   Personal Auto   Personal L3
33  Corporate Auto  Corporate L2
34  Corporate Auto  Corporate L1
35   Personal Auto   Personal L1
36   Personal Auto   Personal L3
37   Personal Auto   Personal L3
38   Personal Auto   Personal L2
39   Personal Auto   Personal L3
40  Corporate Auto  Corporate L3
41  Corporate Auto  Corporate L3
42   Personal Auto   Personal L2
43   Personal Auto   Personal L2
44    Special Auto    Special L2
45   Personal Auto   Personal L2
46   Personal Auto   Personal L3
47   Personal Auto   Personal L2
48  Corporate Auto  Corporate L2
49   Personal Auto   Personal L2

In [10]:
# Check number of unique values in each column, can they be combined in any way to ease encoding? 

categorical_df.describe(include='all').transpose()

                  count unique            top  freq
customer           9134   9134        BU79786     1
state              9134      5     California  3150
response           9134      2             No  7826
coverage           9134      3          Basic  5568
education          9134      5       Bachelor  2748
effective_to_date  9134     59        1/10/11   195
employmentstatus   9134      5       Employed  5698
gender             9134      2              F  4658
location_code      9134      3       Suburban  5779
marital_status     9134      3        Married  5298
policy_type        9134      3  Personal Auto  6788
policy             9134      9    Personal L3  3426
renew_offer_type   9134      4         Offer1  3752
sales_channel      9134      4          Agent  3477
vehicle_class      9134      6  Four-Door Car  4621
vehicle_size       9134      3        Medsize  6424

In [11]:
# Comment your thoughts and make those changes.


# The columns 'policy' and 'policy_type' can be combined. I chose to keep the first because it has more info
categorical_df = categorical_df.drop('policy_type', axis=1)

In [12]:
# Save the cleaned catagorical dataframe as categorical.csv You will use this file again this week.

In [13]:
categorical_df.to_csv("categorical.csv", index=False)